id = "mojo"
name = "Mojo"
version = "0.0.1"
schema_version = 1
authors = ["Esteban Ginez. <175813+eginez@users.noreply.github.com>"]
description = "Mojo language support for Zed."
repository = "https://github.com/eginez/mojo-zed-extension"

[grammars.mojo]
repository = "https://github.com/lsh/tree-sitter-mojo"
rev = "564d5a8489e20e5f723020ae40308888699055c0"

[language_servers.mojo-lsp-server]
name = "Mojo Language Server"
language = "Mojo"
